name: icanteenlib
description: Experimentální **neoficiální** webscrape knihovna pro komunikaci se systémem [iCanteen](https://www.z-ware.cz/internetove-objednavky)
version: 4.2.0
repository: 'https://github.com/Autojidelna/icanteenlib'
issue_tracker: 'https://github.com/Autojidelna/icanteenlib/issues'

environment:
  sdk: '>=3.9.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.13
  dotenv: ^4.0.1
  freezed: ^3.2.3
  json_serializable: ^6.9.0
  lints: ^6.0.0
  test: ^1.16.0

dependencies:
  http: ^1.1.0
  html: ^0.15.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
