name: icanteenlib
description: Experimentální **neoficiální** webscrape knihovna pro komunikaci se systémem [iCanteen](https://www.z-ware.cz/internetove-objednavky)
version: 5.0.0
repository: 'https://github.com/Autojidelna/icanteenlib'
issue_tracker: 'https://github.com/Autojidelna/icanteenlib/issues'
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.10.1
  dotenv: ^4.2.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3

dependencies:
  http: ^1.5.0
  html: ^0.15.6
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
